karma.py

* bot now doesn't forget karma after restart
* fixed karma_inc and karma_dec, so if there is not
user already registered in DB, bot won't throw
exception

karma: saving karma into database

---

travel.py

* Added an option to search for combined means of transportation (that
is bus+train) viac cpsk.
--------------------------------------------
I am not sure whether `spoj` is the right keyword here but I believe we certainly need this.

travel: Added spoj option

---

basic.py

* return error message when exception is raised

eval: added SyntaxError and ValueError handler

---

sticky_notes.py

* Fixed a few typos.
* Fixed note appending.
* Fixed situations when a nick might not have any notes prepared.

sticky-notes: A few small fixes

---

sticky_notes.py

Signed-off-by: Peter Polacik <polacik.p@gmail.com>

update: Changed sticky note message format.

---

sticky_notes.py

sn: Added command to list notes for a given nick.

---

basic.py

* modified lordpotatoe's nick
* added float and int into eval

basic: small janitoring and eval fix

---

.travis.yaml

* Added a basci Travis CI file in order to start with continous
integration (even if just by enforcing some formatting rules).

test: Added .travis.yaml file

---

sticky_notes.py
travel.py

* Removed unused imports from sticky_notes and travel.

janitoring: Removed unused imports

---

.travis.yml
travel.py
url_matcher.py

* Removed trailing whitespace from url_matcher.py

janitoring: Removed trailing whitespace

---

karma.py

karma: Fixed PEP8 issues.

---

weather.py

janitoring: pep8 issues (#61)

---

karma.py

* Added a very simple example that should showcase the usage of the
change_cmd function.

update: Added krm shortcut for karma

---

travel.py
weather.py

* There is now a helper function split_args_by for what we previously
did via some magical map call.

update: Moved to split_args_by where possible

---

README.md

* Added a few rudimentary installation steps to README.md so that any
random passer-by won't get lost right away.

update: Added installation steps to README.md

---

CONTRIBUTORS
LICENSE

* Added proper attribution file to LICENSE and also added contributors
to CONTRIBUTORS.

update: Fixed LICENSE, added CONTRIBUTORS

---

LICENSE

janitoring: Fixed typo in LICENCE.

---

basic.py

* Added s/pattern/repl/ type of substitutions for in-channel commands
and messages directed at a bot.

update: Added sed substitution of the last message

---

basic.py

* Added a reprocess command which kind of 'repeats' the last command or
a message of a user to a given bot.

basic: Added a reprocess command

---

basic.py

basic: Consolidated docstring quotation marks.

---

basic.py

* Added sub command which encapsulates 'sed substitution' in a command.
* Moved the regular expression which matches the sed substitution
syntax into a separate variable.
* Did some janitoring throughout the file.

basic: Added sub command

---

karma.py

karma: Option to list N users with most karma.

---

vote.py

* ability to vote to kick/ban/mute user.
others are able to agree !yes or disagree !no
* ability to ask yes/no question.
* ability to ask question expecting some answer.
* showing results after vote is finished

vote: vote to kick, ban, mute, ask question

---

requirements.txt

* Added `brutal-ng` to requirements while also making sure that its of
the last version which has all the new features brutal-plugins depends
on.

update: Added brutal-ng to requirements

---

sticky_notes.py

sn: Added object with more info about the note.

---

vote.py

* there was trailing comma at the end

vote: nicer format on results of `ask` cmd

---

sticky_notes.py

* Ffixed sticky note listing -- only users with existing sticky notes
should be listed. Fixes #90.

sn: Fixed sticky note listing

---

sticky_notes.py

sn: Added command to delete last note from user.

---

last_seen.py

Issue: #95 
To: @mrshu 
Cc: @Adman @pepol 
Signed-off-by: Jakub Novak <jakub.novak@gmail.com>

ls: Added cmd to check when user was last seen.

---

last_seen.py

* using datetime library instead of time
* if the user was seen less than 24 hours ago,
it shows just `x hours and y minutes ago`

last_seen: updated return message

---

url_matcher.py

* Sometimes there is (obviously) no 'content-length'. This commit tries
to prevent those situations when it could be missing.

url_matcher: Fixed issues with file size check

---

requirements.txt

* Pin new version of cpsk module that adds delays of trains.

requirements: Pin cpsk's new version

---

last_seen.py

* Fixed an indent issue in last_seen.py that was breaking the Travis
tests (pyflakes).

update: Fixed Travis tests

---

dayinfo.py
requirements.txt

* shows weekday, date, nameday, holiday and
international day
* possibility to make other countries config

sup: know the info about current day

---

dayinfo.py

hotfix: dayinfo now shows holidays

---

travel.py

* also did a little janitoring to prevent
same function calls on multiple places

travel: added option to search for next line

---

url_matcher.py

* The size was previously comparing strings and integers which just does
not work well.

url_matcher: Fixed webpage size check

---

requirements.txt
rss.py

* Added first version of RSS plugin which periodically looks for updates
in given RSS feeds and prints them to all channels to which its bot is
connected.

update: Added first version of RSS plugin

---

rss.py

* Changed the way new entries are being checked/found by comparing their
hashes. The hash is composed of the following:
- Entry ID
- Entry Title
- Entry URL

rss: Better new entries check with hashing

---

rss.py

* Added cache clearing for hashed entries that are stored locally.

rss: Add cache clearing

---

dayinfo.py

also created a helper function which takes care of date validation

dayinfo: added nameday command

---

hladny_matfyzak.py
requirements.txt

hm: daily food choices for students in Mlyny
